services:

  server:
    # location to find dockerfile
    build: ./tsearch/
    ports:
      # exposes [localhostPort]:[containerPort]
      - "8000:9999"

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
