[package]
name = "scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
postgres = "0.19.10"
db = { path = "../db" }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
