[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
postgres = "0.19.10"
db = { path = "../db" }
bollard = "0.19.1"
